---
- name: Copy Secure Boot Key and CRT
  block:
    - copy: src=etc/secureboot dest=/mnt/etc/ owner=root group=root mode=0600
    - copy: src=etc/pacman.d dest=/mnt/etc/ owner=root group=root
    - copy: src=boot/client dest=/mnt/boot/ owner=root group=root mode=0600
    - template: src=sbupdate.j2 dest=/mnt/etc/default/sbupdate
    - shell: arch-chroot /mnt pacman -Sy 
    - shell: arch-chroot /mnt pacman -S sbupdate-git --noconfirm
    # Need to confirm fwupd package doesn't overwrite this.. or just deploy latter 
    - template: src=uefi.conf.j2 dest=/mnt/etc/fwupd/uefi.conf
    - shell: arch-chroot /mnt /usr/bin/sbupdate
    
# Keep systemd-boot install for backup 
- name: Intall bootctl loader
  command: arch-chroot /mnt bootctl --path=/boot install
- name: Configure systemd-boot loader conf
  copy:
    src: loader.conf
    dest: "{{efiloc}}/loader/loader.conf"
- name: Configure archlinux entry
  copy:
    src: arch.conf
    dest: "{{efiloc}}/loader/entries/arch.conf"
- import_tasks: bios.yml
  tags: [bios]
